version: '3.8'

services:
  #___________Microservice Authentification
  backend-auth:
    build: ./authentification
    restart: always
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cvkd3o9r0fns739q3n3g-a.frankfurt-postgres.render.com:5432/assurmob_r21b
      SPRING_DATASOURCE_USERNAME: assurmob_r21b_user
      SPRING_DATASOURCE_PASSWORD: 33ZJ9h9ipXQeiznN11igs3hzbuweMS2B
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - byteco-network

  #___________Microservice Gestion des utilisateurs
  backend-gestionutilisateurs:
    build: ./gestionutilisateurs
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cvkd3o9r0fns739q3n3g-a.frankfurt-postgres.render.com:5432/assurmob_r21b
      SPRING_DATASOURCE_USERNAME: assurmob_r21b_user
      SPRING_DATASOURCE_PASSWORD: 33ZJ9h9ipXQeiznN11igs3hzbuweMS2B
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - byteco-network

  #___________Microservice Gestion des Contrats
  backend-gestioncontrat:
    build: ./gestioncontrats
    restart: always
    ports:
      - "8086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cvkd3o9r0fns739q3n3g-a.frankfurt-postgres.render.com:5432/assurmob_r21b
      SPRING_DATASOURCE_USERNAME: assurmob_r21b_user
      SPRING_DATASOURCE_PASSWORD: 33ZJ9h9ipXQeiznN11igs3hzbuweMS2B
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - byteco-network

  #___________Microservice Gestion des Offres
  backend-gestionoffre:
    build: ./gestionoffre
    restart: always
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cvkd3o9r0fns739q3n3g-a.frankfurt-postgres.render.com:5432/assurmob_r21b
      SPRING_DATASOURCE_USERNAME: assurmob_r21b_user
      SPRING_DATASOURCE_PASSWORD: 33ZJ9h9ipXQeiznN11igs3hzbuweMS2B
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - byteco-network

  #___________Microservice Empreinte Carbone
  backend-empreintecarbone:
    build: ./empreintecarbone
    restart: always
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cvkd3o9r0fns739q3n3g-a.frankfurt-postgres.render.com:5432/assurmob_r21b
      SPRING_DATASOURCE_USERNAME: assurmob_r21b_user
      SPRING_DATASOURCE_PASSWORD: 33ZJ9h9ipXQeiznN11igs3hzbuweMS2B
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - byteco-network

  #___________Microservice Gestion des Sinistres (commenté pour l’instant)
  backend-gestionsinistres:
    build: ./gestionsinistres
    restart: always
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cvkd3o9r0fns739q3n3g-a.frankfurt-postgres.render.com:5432/assurmob_r21b
      SPRING_DATASOURCE_USERNAME: assurmob_r21b_user
      SPRING_DATASOURCE_PASSWORD: 33ZJ9h9ipXQeiznN11igs3hzbuweMS2B
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - byteco-network

  #___________Frontend
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/code/src
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/src:/code/src
      - /project/node_modules
    networks:
      - byteco-network
    depends_on:
      - backend-auth

#___________Volumes
volumes:
  db-auth-data: {}
  db-gestionutilisateurs-data: {}
  db-gestioncontrat-data: {}
  db-gestionoffre-data: {}
  db-gestionsinistres-data: {}

#___________Secrets
secrets:
  db-password-auth:
    file: ./authentification/db/password.txt
  db-password-gestionutilisateurs:
    file: ./gestionutilisateurs/db/password.txt
  db-password-gestionsinistres:
    file: ./gestionsinistres/db/password.txt

#___________Networks
networks:
  byteco-network:
    driver: bridge